"""Markdown export for family tree documentation.

Generates human-readable Markdown files suitable for:
- GitHub/GitLab documentation
- Wiki pages
- Static site generators (Jekyll, Hugo, MkDocs)
- Personal genealogy documentation
- GPS compliance reports
"""
from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from dataclasses import dataclass, field
from typing import Any

from gps_agents.ledger.fact_ledger import FactLedger
from gps_agents.models.fact import Fact, FactStatus


@dataclass
class MarkdownPerson:
    """Person data for Markdown export."""

    key: str
    name: str
    given_name: str | None = None
    surname: str | None = None
    facts: list[Fact] = field(default_factory=list)
    parents: list[str] = field(default_factory=list)
    spouses: list[str] = field(default_factory=list)
    children: list[str] = field(default_factory=list)


def _parse_person_key(person_key: str) -> tuple[str, str | None, str | None]:
    """Parse person_id key into name components."""
    parts = person_key.split("|")
    name_part = parts[0].strip() if parts else ""

    if not name_part:
        return "Unknown", None, None

    name_parts = name_part.split()
    if len(name_parts) == 1:
        return name_part, name_part, None
    else:
        given = " ".join(name_parts[:-1])
        surname = name_parts[-1]
        return name_part, given, surname


def _format_date(date_str: str | None) -> str:
    """Format date string for display."""
    if not date_str:
        return "Unknown"
    return date_str


def _fact_to_markdown(fact: Fact) -> str:
    """Convert a fact to Markdown text."""
    lines = []
    fact_type = (fact.fact_type or "").title()
    lines.append(f"- **{fact_type}**: {fact.statement}")

    if fact.sources:
        for src in fact.sources:
            if src.url:
                lines.append(f"  - Source: [{src.title or 'Link'}]({src.url})")
            elif src.title:
                lines.append(f"  - Source: {src.title}")

    return "\n".join(lines)


def export_markdown(
    ledger_dir: Path,
    out_file: Path,
    title: str = "Family Tree",
    include_sources: bool = True,
    include_table_of_contents: bool = True,
    group_by_surname: bool = True,
) -> Path:
    """Export facts and relationships to Markdown format.

    Args:
        ledger_dir: Path to the fact ledger directory
        out_file: Output file path for the Markdown file
        title: Document title
        include_sources: Include source citations
        include_table_of_contents: Include auto-generated TOC
        group_by_surname: Group persons by surname

    Returns:
        Path to the created Markdown file
    """
    ledger = FactLedger(str(ledger_dir))

    persons: dict[str, MarkdownPerson] = {}

    def _ensure_person(person_key: str) -> MarkdownPerson:
        """Ensure person exists and return it."""
        if person_key not in persons:
            full_name, given, surname = _parse_person_key(person_key)
            persons[person_key] = MarkdownPerson(
                key=person_key,
                name=full_name,
                given_name=given,
                surname=surname,
            )
        return persons[person_key]

    # Process all accepted facts
    for fact in ledger.iter_all_facts(FactStatus.ACCEPTED):
        fact_type = (fact.fact_type or "").lower()

        if fact_type == "relationship":
            subject = (fact.relation_subject or "").strip()
            obj = (fact.relation_object or "").strip()
            kind = (fact.relation_kind or "").lower()

            if subject and obj:
                subject_person = _ensure_person(subject)
                obj_person = _ensure_person(obj)

                if kind == "parent_of":
                    subject_person.children.append(obj)
                    obj_person.parents.append(subject)
                elif kind == "child_of":
                    subject_person.parents.append(obj)
                    obj_person.children.append(subject)
                elif kind == "spouse_of":
                    if obj not in subject_person.spouses:
                        subject_person.spouses.append(obj)
                    if subject not in obj_person.spouses:
                        obj_person.spouses.append(subject)

        elif fact.person_id:
            person = _ensure_person(fact.person_id)
            person.facts.append(fact)

    # Generate Markdown
    lines: list[str] = []

    # Header
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"*Generated by gps-genealogy-agents on {datetime.now(UTC).strftime('%Y-%m-%d')}*")
    lines.append("")

    # Statistics
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Total Individuals**: {len(persons)}")

    surnames = set(p.surname for p in persons.values() if p.surname)
    lines.append(f"- **Distinct Surnames**: {len(surnames)}")
    lines.append("")

    # Table of Contents
    if include_table_of_contents:
        lines.append("## Table of Contents")
        lines.append("")

        if group_by_surname:
            for surname in sorted(surnames):
                safe_anchor = surname.lower().replace(" ", "-")
                lines.append(f"- [{surname}](#{safe_anchor})")
        else:
            for person in sorted(persons.values(), key=lambda p: p.name):
                safe_anchor = person.name.lower().replace(" ", "-").replace("/", "")
                lines.append(f"- [{person.name}](#{safe_anchor})")

        lines.append("")

    # Person entries
    lines.append("## Individuals")
    lines.append("")

    if group_by_surname:
        # Group by surname
        by_surname: dict[str, list[MarkdownPerson]] = {}
        for person in persons.values():
            surname = person.surname or "Unknown"
            if surname not in by_surname:
                by_surname[surname] = []
            by_surname[surname].append(person)

        for surname in sorted(by_surname.keys()):
            lines.append(f"### {surname}")
            lines.append("")

            for person in sorted(by_surname[surname], key=lambda p: p.name):
                lines.extend(_person_to_markdown(person, include_sources))
                lines.append("")

    else:
        # Alphabetical order
        for person in sorted(persons.values(), key=lambda p: p.name):
            lines.extend(_person_to_markdown(person, include_sources))
            lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*This document was generated using [GPS Genealogy Agents](https://github.com/thomasvincent/gps-genealogy-agents)*")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(lines), encoding="utf-8")
    return out_file


def _person_to_markdown(person: MarkdownPerson, include_sources: bool) -> list[str]:
    """Convert a person to Markdown lines."""
    lines = []

    lines.append(f"#### {person.name}")
    lines.append("")

    # Basic info
    if person.given_name or person.surname:
        lines.append(f"**Name**: {person.given_name or ''} {person.surname or ''}")
        lines.append("")

    # Family relationships
    if person.parents:
        lines.append("**Parents**:")
        for parent in person.parents:
            lines.append(f"- {parent}")
        lines.append("")

    if person.spouses:
        lines.append("**Spouse(s)**:")
        for spouse in person.spouses:
            lines.append(f"- {spouse}")
        lines.append("")

    if person.children:
        lines.append("**Children**:")
        for child in person.children:
            lines.append(f"- {child}")
        lines.append("")

    # Facts
    if person.facts:
        lines.append("**Facts**:")
        lines.append("")

        for fact in person.facts:
            fact_type = (fact.fact_type or "").title()
            lines.append(f"- **{fact_type}**: {fact.statement}")

            if include_sources and fact.sources:
                for src in fact.sources:
                    if src.url:
                        lines.append(f"  - Source: [{src.title or 'Link'}]({src.url})")
                    elif src.title:
                        lines.append(f"  - Source: {src.title}")

        lines.append("")

    return lines


def export_markdown_report(
    persons: list[dict[str, Any]],
    relationships: list[dict[str, Any]],
    out_file: Path,
    title: str = "Family Tree Report",
    include_gps_compliance: bool = True,
) -> Path:
    """Export a formatted Markdown report from pre-structured data.

    Args:
        persons: List of person dictionaries
        relationships: List of relationship dictionaries
        out_file: Output file path
        title: Report title
        include_gps_compliance: Include GPS compliance section

    Returns:
        Path to the created Markdown file
    """
    lines = []

    # Header
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"*Report generated on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}*")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Individuals | {len(persons)} |")
    lines.append(f"| Total Relationships | {len(relationships)} |")
    lines.append("")

    # GPS Compliance Section
    if include_gps_compliance:
        lines.append("## GPS Compliance")
        lines.append("")
        lines.append("This report follows the [Genealogical Proof Standard](https://www.bcgcertification.org/resources/standard/):")
        lines.append("")
        lines.append("1. **Reasonably Exhaustive Search**: Sources searched are documented below")
        lines.append("2. **Complete Citation**: All facts include source citations")
        lines.append("3. **Evidence Analysis**: Facts have been evaluated for relevance")
        lines.append("4. **Conflict Resolution**: Conflicting evidence is noted")
        lines.append("5. **Written Conclusion**: This document serves as the written proof argument")
        lines.append("")

    # Persons
    lines.append("## Individuals")
    lines.append("")

    for person in persons:
        name = person.get("name", "Unknown")
        lines.append(f"### {name}")
        lines.append("")

        if person.get("birth_date") or person.get("birth_place"):
            birth = f"{person.get('birth_date', '?')} in {person.get('birth_place', '?')}"
            lines.append(f"**Birth**: {birth}")
            lines.append("")

        if person.get("death_date") or person.get("death_place"):
            death = f"{person.get('death_date', '?')} in {person.get('death_place', '?')}"
            lines.append(f"**Death**: {death}")
            lines.append("")

        if person.get("notes"):
            lines.append("**Notes**:")
            for note in person["notes"]:
                lines.append(f"- {note}")
            lines.append("")

        if person.get("sources"):
            lines.append("**Sources**:")
            for src in person["sources"]:
                if src.get("url"):
                    lines.append(f"- [{src.get('title', 'Source')}]({src['url']})")
                else:
                    lines.append(f"- {src.get('title', 'Unknown source')}")
            lines.append("")

    # Relationships
    if relationships:
        lines.append("## Relationships")
        lines.append("")
        lines.append("| Type | Subject | Object |")
        lines.append("|------|---------|--------|")
        for rel in relationships:
            lines.append(f"| {rel.get('type', '?')} | {rel.get('subject', '?')} | {rel.get('object', '?')} |")
        lines.append("")

    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(lines), encoding="utf-8")
    return out_file
